name: WorkshopPlugin
version: 1.0.0
author: hugobaret
main: com.github.hugobaret.pluginmc.WorkshopPlugin

commands:
  epitech:
    description: "Vous donne -42 de la part de Marvin :)"
    usage: /<command>
